name: Build & Deploy Storybook
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install & Build
        run: npm ci && npm run build-storybook
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
